create table if not exists notes (
  id bigint generated by default as identity primary key,
  subject_key text not null,
  topic_key text not null,
  subject text,
  topic text,
  content text not null,
  key_points jsonb,
  updated_at timestamptz default now(),
  unique (subject_key, topic_key)
);

alter table notes enable row level security;

create policy "Allow read notes"
on notes
for select
using (true);
